Youtube integration error
raccoongang/videojs-offset pull request #1
Opened 2016-12-05 09:57 UTC by xahgmah

To avoid RuntimeError: Maximum call stack size exceeded(…)

2016-12-05 13:55 UTC, z4y4ts commented on dist/videojs-offset.js
> +        this.pause();
Leave only this line with `this.pause();` and remove the rest of this if-branch.
As discussed, we don't need it.

2016-12-05 15:03 UTC, z4y4ts approved these changes

2016-12-05 15:06 UTC, polesye requested changes

2016-12-05 15:06 UTC, polesye commented on dist/videojs-offset.js
> +    var update_time = new Date();
use camelCase

2016-12-05 15:06 UTC, polesye commented on dist/videojs-offset.js
> +    if (this.lustUpdateTime==undefined || update_time-this.lustUpdateTime>1000) {
typo `lust`

2016-12-05 15:48 UTC, z4y4ts commented
Good commit message here would be:
> Handle 'timeupdate' event only once a second
> 
> To prevent infinite loop caused by calling setCurrentTime() inside a handler.

2016-12-05 15:58 UTC, polesye commented on dist/videojs-offset.js
> +    var updateTime = new Date();
```js
    if (new Date() - (this.lastTimeUpdate || 0) < 1000) return;
    this.lastTimeUpdate = new Date();
    var curr = this.currentTime();
    if (curr < 0) {
      this.currentTime(0);
      this.play();
    }
    if (this._offsetEnd > 0 && (curr > (this._offsetEnd - this._offsetStart))) {
      this.pause();
      if (!this._restartBeginning) {
        this.currentTime(this._offsetEnd - this._offsetStart);
      } else {
        this.trigger('loadstart');
        this.currentTime(0);
      }
    }
```

it should produce less diff

2016-12-06 14:14 UTC, polesye commented on dist/videojs-offset.js
> +    var updateTime = new Date();
@xahgmah FYI^^

2016-12-07 10:33 UTC, polesye approved these changes
Please squash all commits and put a good commit message before merge.

2016-12-08 15:25 UTC, merged